<a href="https://colab.research.google.com/github/2025csmutturajparappaneelannavard-spec/DAV_LAB/blob/main/LAB1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr=np.array([10,20,30,40,50])

In [ ]:
print("Numpy array is ",arr)

Numpy array is  [10 20 30 40 50]


In [ ]:
print("First element:",arr[0])

First element: 10


In [ ]:
print("Last element:",arr[-1])

Last element: 50


In [ ]:
print(arr[0:3])

[10 20 30]


In [ ]:
print(arr[-1:])

[50]


In [ ]:
print(arr[-3:])

[30 40 50]


In [ ]:
print("Add 5:",arr+5)

Add 5: [15 25 35 45 55]


In [ ]:
print("Multiply by 5:",arr*5)

Multiply by 5: [ 50 100 150 200 250]


In [ ]:
print("Sum:",np.sum(arr))

Sum: 150


In [ ]:
print("Mean:",np.mean(arr))

Mean: 30.0


In [ ]:
print("Maximum:",np.max(arr))

Maximum: 50


In [ ]:
reshape=arr.reshape(5,1)
print(reshape)

[[10]
 [20]
 [30]
 [40]
 [50]]


In [ ]:
import pandas as pd

In [ ]:
data={ "Name":["Rahul","Mbappe","Cristiano"],
      "Marks":[11,22,7],
      "Branch":["CSE","ECE","FOOTBALL"]}

In [ ]:
df=pd.DataFrame(data)
print(df)

        Name  Marks    Branch
0      Rahul     11       CSE
1     Mbappe     22       ECE
2  Cristiano      7  FOOTBALL


In [ ]:
print(df["Marks"])

0    11
1    22
2     7
Name: Marks, dtype: int64


In [ ]:
print(df["Name"])

0        Rahul
1       Mbappe
2    Cristiano
Name: Name, dtype: object


In [ ]:
print("First row using row:")
print(df.iloc[0])

First row using row:
Name      Rahul
Marks        11
Branch      CSE
Name: 0, dtype: object


In [ ]:
print("First person marks:",df.iloc[0,1])

First person marks: 11


In [ ]:
print("Row slicing of first two rows:")
print(df.iloc[0:2])

Row slicing of first two rows:
     Name  Marks Branch
0   Rahul     11    CSE
1  Mbappe     22    ECE


In [ ]:
print("Both row and coln slicing")
print(df.iloc[0:3,[0,1]])

Both row and coln slicing
        Name  Marks
0      Rahul     11
1     Mbappe     22
2  Cristiano      7


In [ ]:
print("Filtering:")
res=df[df["Marks"]>9]
print("Students with marks greater than 9:")
print(res)

Filtering:
Students with marks greater than 9:
     Name  Marks Branch
0   Rahul     11    CSE
1  Mbappe     22    ECE


In [ ]:
arr1=np.array([10,20],[30,40])
print(np.shape(arr1))